// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voyuwwedtxoiwioeuhoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZveXV3d2VkdHhvaXdpb2V1aG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NzM1NzAsImV4cCI6MjA1NjA0OTU3MH0.rIYFdOc_-rvwrgeoIYQ4VkKUJpTYlA9fbf_HZ8kYeGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);